### ISSUE TITLE
Rewriting vote to use USB card reader instead of Serial port.

### ISSUE THREAD

**Issue by tofarstad** [webkom/vote#226]
Hey, I'm currently working on getting vote to work on my computer. I bought a card reader from HID, which connects to my computer via USB, I see now when I examine your code, that the program only supports Serial ports. And I've been trying to rewrite it myself, but can't seem to find the right answer.

**Comment by ekmartin** [comment]
Hi - the readers we use are connected with USB as well, we just use the [chrome.serial](https://developer.chrome.com/apps/serial) API to read from them. When you open the chrome app (in the `chrome_app` folder) there should be a toolbar at the bottom where you can select the port, which is usually something like `/dev/ttyUSB0`. Is there anything in this list at all?
