### ISSUE TITLE
Tab to logout

### ISSUE THREAD

**Issue by SmithPeder** [webkom/vote#284]
When on the register page everybody uses `TAB` to go down to the next input field. After the username, password, register and so forth fields the next `TAB` will jump down to the bottom of the page. At the bottom of the page is the `logout` button. So if you `TAB` one tab too much and press enter the moderator user will be logged out, which sucks.

**Comment by odinuge** [comment]
https://stackoverflow.com/questions/2757973/can-i-ignore-some-website-element-when-navigating-using-the-tab-key
