### ISSUE TITLE
List of "usage"

### ISSUE THREAD

**Issue by odinuge** [webkom/vote#289]
Create a list where everyone can make a PR to add (eg.) the following about an event where they used `vote`:
- Name of organization (maye together with a logo)
- Event (`generalforsamling`, `ledervalg` etc.)
- Where
- Users
- Date

**Comment by SmithPeder** [comment]
Any thoughts of how we should do this? Could maybe make a new route like `vote.abakus.no/usage`, then a create a format where people easily can make their PR to enter the list. We could also link the route in the footer, like `Logg ut | Made by webkom | For Abakus | View Usage`
