### ISSUE TITLE
Deactivate/reactivate card alert too small

### ISSUE THREAD

**Issue by SmithPeder** [webkom/vote#311]
I remember this from last Genfors. The alert that pops up when a user scans their card to leave(enter) is too small. So every time someone scans you have to explain that it's okay to leave(or enter).

**Comment by odinuge** [comment]
:+1: 

Maybe we can just make them ~fullscreen?

**Comment by SmithPeder** [comment]
Yeah, I think that can be a good solution! Or maybe just almost fullscreen so we don't need to rewrite the layout files. I don't wanna write `.pug` and `.styl` no more 👎
