### ISSUE TITLE
Unit tests for STV logic

### ISSUE THREAD

**Issue by LudvigHz** [webkom/vote#350]
Add unit tests to STV logic.
We want to cover all possible cases and the various edge cases.

This includes writing a framework to define test cases as simply as possible.

We can use test cases from previous, real-world elections and examples from various articles.

**Comment by SmithPeder** [comment]
I've written a unit test schema for STV _(see below)_. This will is a shorthand method of writing the full election. Here the ballots reduced down to the permutations and the test runner will expand it up to the original size _(how it would have looked if the election was real, and on the format the `elect()` method wants it)_

The test runner for SVT login will read the dataset and:

1. Create an `Election` with two seats
2. Create one `Alternative` for each alternative
3. Add the alternatives to the election
4. Repeat and flatmap the priorities such that the `String` is resolved into the corresponding mongdb `Alternative`
5. Create `Votes` for each priority list
6. Add all the votes to the `Election`

Then it will call the `election.elect()` method to get the electionn result, and run assertions on that result.

```js
module.exports = {
    seats: 2,
    alternatives: ['Andrea', 'Carter', 'Brad'],
    priorities: [{
        priority: ['Andrea', 'Carter'],
        amount: 45,
    }, {
        priority: ['Carter'],
        amount: 25,
    }, {
        priority: ['Brad'],
        amount: 30,
    }, ],
};
```

I have found and created tests for the 3 datasets below _(some of them are examples in the wiki)_. If anyone finds some other nice datasets, please write down the link so we can implement them later.
- https://en.wikipedia.org/wiki/Droop_quota
- https://en.wikipedia.org/wiki/Single_transferable_vote
- https://www.iiconsortium.org/Single_Transferable_Vote.pdf

**Comment by SmithPeder** [comment]
Just found this page https://www.opavote.com/results/5654402576678912/2
It has results and one can download full ballots.

You can also switch between multiple official types of STV
![image](https://user-images.githubusercontent.com/23152018/99911736-b4184b00-2cf6-11eb-8fa5-ef02e0c1f8d5.png)
