### ISSUE TITLE
Add STV logic to database models

### ISSUE THREAD

**Issue by LudvigHz** [webkom/vote#351]
Add/edit database schema to fit STV.

- [x] Number of seats in an election.
- [x] Priority Votes. 1st, 2nd, 3rd priority etc.

**Comment by SmithPeder** [comment]
The initial implementation is done like this.

The difference is "What is an alternative". Before you would vote for an `alternative` so the alternative model had the `addVote()` method. With STV this does not make sense, as one does not vote on an Alternative, but rather a ballot comprising of multiple alternatives in a given order.

Therefore the new implementation `POST` on the election itself, and creates a vote in the `votes` list. This vote will have an ordered list of priorities, which is from the same set as the alternatives the election has.

The new `addVote()` method is therefore located on the electionSchema, and it takes a User and a list of priorities as parameters. 

![image](https://user-images.githubusercontent.com/23152018/99463889-14923b80-2937-11eb-8afc-26e235bcaeb5.png)
