### ISSUE TITLE
Basic user view for choosing canditates

### ISSUE THREAD

**Issue by LudvigHz** [webkom/vote#353]
In an STV election, we need a UI to allow users to easily prioritize the number of candidates they want.

Some propositions.

- User is presented with a list of the candidates. They can then click on the number of candidates they want where the first one they click is the 1st priority etc.
- User is presented with a list, where they can drag and drop the candidates onto a priority list, as well as reorder the list with drag and drop

**Comment by LudvigHz** [comment]
After some discussion, we have an idea for how this should work:

The user is presented with a list of the candidates, as well as on option to choose "blank" The blank option may be separated from the other options.

The user has two choices:
1. Select `1 - n` candidates from the list, where `n` is the number of seats.
2. Select `blank`, and thus opt not to choose any candidates in the election.

### Option 1
The user clicks on a candidate in the list. The `blank` option is greyed out, making it clear that it is not possible to choose it anymore. The user may choose up to `n-1` other candidates from the list now. The candidates are prioritized in the order the user clicks on the alternative.
The user should also have have the option to easily reorder the list  afterwards.
The submitted list should then be the prioritized list of candidates the user has chosen.

### Option 2
The user clicks on the `blank` alternative. The list of alternatives is greyed out, making it clear that it is not possible to choose any of them. upon submitting, this is in effect the same as sending an empty list of alternatives. The blank option is there to make is clear to the user that he/she is voting blank.

**Comment by SmithPeder** [comment]
Closed in #374
