### ISSUE TITLE
Validation/persmission for STV

### ISSUE THREAD

**Issue by LudvigHz** [webkom/vote#362]
Related issues: #361 

**Requirements**
The backend should validate requests and send meaningful error messages. The frontend should also handle these properly.

Some of the things we need to think about:
- [x] A vote should not contain more alternatives than there are possible seats in the election.
- [x] All alternatives need to exist on the election.
- [x] The election should not be closed. (Should already exist. But just make sure this is the case today as well)
- [x] All alternatives in the vote must be unique.
- [x] Make sure existing validation still holds in the new implementation.

**Comment by SmithPeder** [comment]
There is also a validation case where the priority list a user sends in contains elements that the alternatives do not. 
Basically a set difference between `priority list` and the `alternatives`. If this set is not empty there is some wired stuff going on.

**Comment by LudvigHz** [comment]
> There is also a validation case where the priority list a user sends in contains elements that the alternatives do not.
> Basically a set difference between `priority list` and the `alternatives`. If this set is not empty there is some wired stuff going on.

Is this different from the case where `priorities` contain alternatives that do not exist on the election?

**Comment by SmithPeder** [comment]
The thing is, no 🙃  But I read that point wrong ups
