### ISSUE TITLE
Deactivate and generate code

### ISSUE THREAD

**Issue by SmithPeder** [webkom/vote#382]
So in addition to #381 we need a way to disable/enable users in a digital setting. We discussed it as follows:
1. Press the "Deaktiver Brukere" when a new discussion or debate starts. That way all the users are unable to vote before activating their account. This generates a new "code" which we will call the activation key.
2. Ask all the members in the **zoom** call to show they are present. All members no present (either by cam/ sound/ raising their hand) will be kicked from the **meeting**. This is equivalent to not allowing anyone in the door when a vote is "ongoing" in the physical world.
3. Before the users can vote in the upcoming election they must enter the activation key, which is distributed in the call either by chat/voice/on screen.
4. This ensures that everyone who votes is present in the call (simulation the real deal)

> This of course does not ensure that someone in the zoom call sends the key to someone that is not present. But one can check that the number of votes exceeds the number of people in the zoom call. It's not perfect, but one will need to say that someone has leaked the code, and redo the election. We feel the chance for this to happen is adequately low, at least if one makes everyone understand that this will be the consequence of "cheating".

**Comment by odinuge** [comment]
Sorry for missing the meeting this week, but here are some insights from my genfors and zoom-meeting experience. 

> Ask all the members in the zoom call to show they are present. All members no present (either by cam/ sound/ raising their hand) will be kicked from the meeting. This is equivalent to not allowing anyone in the door when a vote is "ongoing" in the physical world.

Hmm. Not sure if I agree about this one. A physical meeting is way different than a virtual one, especially when it can potentially last 6-8-10 hours. It do depend on the time given to give feedback, but imo. it is unfair to kick out people who are away at a given point in the middle of genfors. One thing is to be away when an election is going to happen, that cant be "fixed", but it is impossible for a pleb to coordinate a toilet visit/coffe fetching/fire alarm/foodora pickup with the exact time we start discussing a new case/the old one is finished. Also, people may be listening in their headset while doing these things, but have a response time bigger than 10sec.

> This generates a new "code" which we will call the activation key.

> Before the users can vote in the upcoming election they must enter the activation key, which is distributed in the call either by chat/voice/on screen.

As far as I can see, the current/initial impl. connects a key to an election, so the election has to be created at the start of the discussion? Or is the idea that we "distribute" the key in the beginning, and people has to write it down? If we distribute it and people have to insert it right before voting, we also solve the first concern^ (but maybe not in the best way, not sure).

> > It's not perfect, but one will need to say that someone has leaked the code, and redo the election. We feel the chance for this to happen is adequately low, at least if one makes everyone understand that this will be the consequence of "cheating".

Hmm, I guess that depends on the definition. If a person is eligible to vote, and get to register/sign up on vote, that user is eligible to vote in a given election, so not sure if it is cheating at all. If we enforce @stud.ntnu.no (that is currently the only thing we validate on abakus.no), we are sure that people never vote multiple times.

I am also not sure if the user count on zoom/webex/teams/hangouts is a good proxy for the users eligible to vote. Some people might have multiple devices connected, eg. both their phones and their laptop, and some might stream it on a TV for their "kollektiv". Not sure how to solve it tho.

I guess however that it is HS ultimately has to decide on most of these things. They arrange genfors, and make the forretningsorden, and this info probably has to be inside there.

**Comment by SmithPeder** [comment]
> Hmm. Not sure if I agree about this one. A physical meeting is way different than a virtual one, especially when it can potentially last 6-8-10 hours. It do depend on the time given to give feedback, but imo. it is unfair to kick out people who are away at a given point in the middle of genfors. One thing is to be away when an election is going to happen, that cant be "fixed", but it is impossible for a pleb to coordinate a toilet visit/coffee fetching/fire alarm/foodora pickup with the exact time we start discussing a new case/the old one is finished. Also, people may be listening in their headset while doing these things, but have a response time bigger than 10sec.

I totally agree. We can't just kick people right away if they are away for 10 sec. The main point is that users shouldn't be able to just stay in the zoom call for 10 hours, then can't come and vote at the last second. One needs to take the "kick" part within reason. One can give them some time to show they are active with the raise hand thingy🤚 . And if they get someone tried to join and the discussion has just been going on for a little time one can of course let them in. I would say it's up to the chairman or someone to decide if the discussion has gone too far for someone to join. I agree that if a large discussion will be ongoing for an hour someone can still join even tho the discussion is 10 min in.

> As far as I can see, the current/initial impl. connects a key to an election, so the election has to be created at the start of the discussion? Or is the idea that we "distribute" the key in the beginning, and people has to write it down? If we distribute it and people have to insert it right before voting, we also solve the first concern^ (but maybe not in the best way, not sure).

The idea is the correct one. The elections can be created whenever you want, even before Genfors starts. The key is linked to the election, yes, but the key is just used to "unlock" the users' accounts and allow them to get elections. This means the thought flow will be a little like this I thought:

![Untitled Diagram](https://user-images.githubusercontent.com/23152018/104840176-083e4680-58c6-11eb-9db7-175a6590d93e.png)

Kinda don't know how to draw flowcharts (_what course was this again, why have I not learned this?_), but as one can see the "activation" just piggybacks on the `WebSocket` request. So you can create a new election (which makes a new code). This can be done when all candidates have finished their pitch, and we know who is running. Then we press the "Aktiver" button. This will send the normal WebSocket req, but all users will get a `403` back, which prompts the access code field. The code is then distributed in the zoom call and when people enter it they do the "same" call to /retrieve, but now with the code. The right code then activates their user and returns the election.

> If we distribute it and people have to insert it right before voting

So yeah, we do this. Right when we activate the election we show the code on the screen or chat or something. I think this will work great.

> If a person is eligible to vote, and get to register/sign up on vote, that user is eligible to vote in a given election, so not sure if it is cheating at all.

Yeah it really does depend on who is eligible to vote in a given election. If we use the definition from last year 

_"Det vil si at medlemmer som ønsker å delta i avstemningen av en sak eller personvalg må være tilstede i salen før saken behandles. Det vil altså ikke være mulig å komme kun til selve voteringen i en sak."_

then I personally mean a person that "does not have the code" is not eligible to vote, as per the "Forretningsorden" which is acclimated(hopefully) at the beginning of Genfors.

> If we enforce @stud.ntnu.no

In practice, we will enforce `@stud.ntnu.no` mail when the user asks for an account. The only reason I made it so the code allows us to write the whole mail is to ensure that someone without studmail also can get an account. This is very far fetched, but alumni can actually come and demand a user. Their user will be verified on abakus.no, but they will no longer have access to their studmail. 

> I am also not sure if the user count on zoom/webex/teams/hangouts is a good proxy for the users eligible to vote

Yeah, this is also a case. Some people may join with multiple devices, and some in households 3 people may be on one computer. There are many edge-cases here and there 👎🏻

**Comment by odinuge** [comment]
> [zoomstuff]

Yeah, agree about what you say. It do however depend on how we allow people to join the call. If people can just join right into, there is probably no need to kick people out, and if people are inactive I see no reason for them to be in the call either. Maybe we are just creating more problems than we have?

> [flowchart]

Yee, nice, cool. Makes it easier to understand the flow :100:

> The idea is the correct one. The elections can be created whenever you want, even before Genfors starts.

Ish, kinda. Often we don't know what should be voted on, and what alternatives should exist. Most of the time we didn't know that before the election was ready to start. Not sure if VOTE allows us to have multiple elections at the same time either..

> I would say it's up to the chairman or someone to decide if the discussion has gone too far for someone to join.

Totally depends on a lot of stuff tho. If a user disconnects we cannot disallow him/her to join again, and keeping track of everyone in the call would be quite cumbersome I guess. How this is done is probably up to HS to decide on tho.

> [...] then I personally mean a person that "does not have the code" is not eligible to vote, as per the "Forretningsorden" which is acclimated(hopefully) at the beginning of Genfors.

Yeah, but that depends on when we distribute the code, and when people can fill it in, and ofc. what the "Forretningsorden" says. Since we at the time of creating the election we don't know the count of the eligible voters (since all users will be deactivated at that time). If a user disconnects from zoom 10sec before the code is shown and the election starts, that means the user cannot vote if he/she is unable to join the call before the code isn't shown anymore/the election is "over". (even tho that would probably not happen).

I at least don't think we can keep the previous version that only people in the call when we start discussing a subject/case can vote. On some occations we may also end up with multiple elections after each other, but in that case we can probably just keep users active. thow.

> Yeah, this is also a case. Some people may join with multiple devices, and some in households 3 people may be on one computer. There are many edge-cases here and there 👎🏻

So we agree that `zoom-users !== eligible voters` then? Because what can we do if the count is bigger for votes than users on zoom? Start all over again, and the same happen? Or do we have to clear users? I think we should make it possible to start activating users _before_ the election should start, to avoid trouble (and ask if all users are "active", so people can ask on zoom if it isn't working), so that we know the count of eligible voters when the first person votes.

**Comment by SmithPeder** [comment]
> Not sure if VOTE allows us to have multiple elections at the same time either...

It can have **both** multiple **active** and **inactive** elections. The "_multiple inactive_" is nice to have and is no problem. The multiple active case should be addressed. In `:master` this is also possible and is really not a good thing. The `/retrive` endpoint uses `.findOne(active=true)` and if there are multiple active elections you don`t know what elections people get (_i got this yesterday and was very confused when my access code didn't work_).
So I think that in general, we should add a line of code that disables activating one election if another one is already active.

<hr/>

For all the other points. I agree that **"How-To-Complete-The-Election"** using this method has some kinks and crevices, but from a technical perspective, I at least think that the access code to vote on an election works pretty well. It adds a simple layer of security that forces people to actually look at the stream and find the code in order to vote. 

How the full zoom call rules are implemented are, as you say, up to HS. I just had some ideas that would hopefully emulate a normal Genfors to the best of our extent. I agree that we can't be too strict. 

People must be able to
- arrive late
- go to the bathroom without being kicked
- not pay attention to every second of the stream
- not be kicked just because they disconnected

Since it is Digital we need to be a little lose with the rules and I think its better that:
People get to vote > People don't get to vote

It's kind of a Type 1 error vs a Type 2 error, where:
- Type 1 error: Someone who really should be able to vote doesn't get to vote
- Type 2 error: Someone who maybe didn't pay attention still gets to vote

People's right to vote still trumps most rules around "presence" and "attention", so avoiding Type 1 errors is the most important. This PR more aims to disable people from getting a VOTE user in the mail, then never even opening the zoom call where Genfors is held.
