### ISSUE TITLE
Add link to howto be doorman in moderator-view

### ISSUE THREAD

**Issue by norbye** [webkom/vote#458]
HOWTO be doorman is written in [notion/webkom/...](https://www.notion.so/abakuswebkom/HOWTO-use-VOTE-9ebb85958fa84e5fad2f61e9b148b942  )
Should be easy to find from the moderator-view of vote to ensure that every step is being done before every election.

**Comment by LudvigHz** [comment]
This is a very webkom-specific thing though and I don't think this belongs in the app. Would be nice to keep the app as general as possible so more people can make use of it :)
